spring.application.name=JwtAuth

jwt.secretKey=qwertyuiop[asdfghjklqwertyuiopasdfghjklscvbnm,erfghnm5tyhjm,ik9uhrdx5rfchokjygfv

#postgres DB setup
spring.datasource.url=jdbc:postgresql://ep-sweet-silence-aphonlb5-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=<username>
spring.datasource.password=<password>
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect